---
- hosts: 172.31.40.49
  become: yes
  tasks:
  - name: i want to display direct linux command
    command: hostname -f
    register: myresult

  - name: i want to display 1st tasks result    
    debug:
      msg: "{{myresult}}"