---
- hosts: 172.31.40.49
  become: yes
  tasks:
  - name: i want to display direct linux command
    command: hostname -f
    register: myresult

  - name: i want to display 1st tasks result    
    debug:
      msg: "{{myresult}}"

  - name: install git 
    apt:
      name: git
      state: present    
    when: myresult.stderr ==""

  - name: install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !=""      