---
- hosts: 172.31.40.49
  become: yes
  tasks:

  - include_tasks: myfiles.yaml 

  - name: install webserver
    apt:
      name: apache2
      state: present


  - name: i want to copy static files into ansible nodes side 
    template:
       src: mystaticfile.html
       dest: /var/www/html/index.html  


  - name: i want to copy dynamic files into ansible nodes
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: Restart webserver


  - name: i want to download files from remote(internet) into nodes side
    get_url:
        url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
        dest: /home/ubuntu/jenkins.war
        force_basic_auth: yes 

  handlers:
    - name: Restart webserver
      service:
        name: apache2
        state: restarted           