---
- hosts: 172.31.40.49
  become: yes
  tasks:

  - include_tasks: myfiles.yaml 

  - name: install webserver
    apt:
      name: apache2
      state: present


  - name: i want to copy static files into ansible nodes side 
    template:
       src: mystaticfile.html
       dest: /var/www/html/index.html   