---
 - hosts: mywebservers
   become: yes
   tasks: 
    - name: i want to install git 
      apt:
       name: git
       state: present 
      when: ansible_os_family =="Debian" 

    - name: i want to install tree 
      apt:
       name: tree
       state: present
      when: ansible_os_family =="RedHat"   
        
