---
# tasks file for mytomcaterole
- include_tasks: myadduser.yaml
- include_tasks: installjava.yaml
- include_tasks: installtomcat.yaml
- include_tasks: permissions.yaml
- include_tasks: tomcatAdminUsers.yaml
- include_tasks: tomcatservice.yaml
- include_tasks: tomcatstart.yaml
- include_tasks: myjavadeploy.yaml
- include_tasks: tomcatrestart.yaml
