---
# tasks file for webrole1
- name: istall webserver
  apt: 
    name: apache2
    state: present
  notify: restartedwebserver  

- name: install git 
  apt:
    name: git
    state: present
  notify: restartedwebserver  
